"""Data model: card templates and printer profiles.

Everything here is plain dataclasses that round-trip through TOML, so a
template saved from the GUI can be edited by hand (or generated by a script)
and loaded back without surprises.
"""

from __future__ import annotations

import copy
import math
import tomllib
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path
from typing import Any

import tomli_w

HOLE_POSITIONS = (
    "top-left",
    "top-center",
    "top-right",
    "center-left",
    "center-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
)
ALIGNMENTS = ("center", "left", "right")
FIT_MODES = ("shrink", "wrap", "none")

DEFAULT_PALETTE = ["#F4EFE6", "#1F2A44", "#C0392B", "#2E7D32", "#F9A825", "#6A1B9A"]


def _from_dict(cls, data: dict[str, Any] | None):
    """Build a dataclass from a dict, ignoring unknown keys (forward compatible)."""
    if data is None:
        return cls()
    types = {f.name: f.type for f in fields(cls)}
    out = {}
    for k, v in data.items():
        if k not in types:
            continue
        t = types[k] if isinstance(types[k], str) else getattr(types[k], "__name__", "")
        if t == "float" and isinstance(v, int) and not isinstance(v, bool):
            v = float(v)
        elif t == "int" and isinstance(v, float) and v.is_integer():
            v = int(v)
        out[k] = v
    return cls(**out)


@dataclass
class Card:
    width: float = 54.0
    height: float = 86.0
    thickness: float = 1.2
    corner_radius: float = 3.0
    # Safe area kept clear of text, measured from the card edge.
    padding: float = 3.0


@dataclass
class Border:
    enabled: bool = True
    width: float = 1.2
    # Distance between the card edge and the outside of the border.
    inset: float = 0.0
    height: float = 0.4
    # Also draw a ring of border around the hanging hole.
    around_hole: bool = True


@dataclass
class Hole:
    enabled: bool = False
    diameter: float = 5.0
    position: str = "top-left"
    # Distance from the card edge(s) to the centre of the hole.
    offset: float = 5.5


@dataclass
class Slot:
    """One line (or block) of text on the card.

    ``text`` is a template string: ``{column}`` pulls a value from the data
    row, and filters can be chained, e.g. ``{expression|kanji}``.
    """

    name: str = "Text"
    text: str = ""
    enabled: bool = True
    font: str = "Noto Sans CJK JP:Bold"
    size: float = 8.0  # em size in mm (like CSS font-size)
    height: float = 0.6  # how far the text is raised above the card
    y: float = 40.0  # vertical centre of the text, mm from the top edge
    align: str = "center"
    x_offset: float = 0.0  # from centre (center) or from the padding edge (left/right)
    max_width: float = 0.0  # 0 = card width minus padding
    fit: str = "shrink"
    min_size: float = 3.0
    max_lines: int = 2
    line_spacing: float = 1.15
    letter_spacing: float = 0.0  # extra mm between characters
    # Furigana: render Anki-style ``漢字[かんじ]`` as ruby above the base text.
    ruby: bool = False
    ruby_scale: float = 0.45
    ruby_gap: float = 0.4


@dataclass
class Template:
    name: str = "Untitled"
    card: Card = field(default_factory=Card)
    border: Border = field(default_factory=Border)
    hole: Hole = field(default_factory=Hole)
    slots: list[Slot] = field(default_factory=list)
    # Colours of the height bands, from the card base upwards.
    palette: list[str] = field(default_factory=lambda: list(DEFAULT_PALETTE))
    # Fonts tried, in order, when a slot's font has no glyph for a character.
    fallback_fonts: list[str] = field(
        default_factory=lambda: ["Noto Sans CJK JP:Bold", "DejaVu Sans:Bold"]
    )

    def copy(self) -> Template:
        return copy.deepcopy(self)

    # -- serialisation ---------------------------------------------------
    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return {"cardsmith": 1, **d}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Template:
        t = cls(
            name=d.get("name", "Untitled"),
            card=_from_dict(Card, d.get("card")),
            border=_from_dict(Border, d.get("border")),
            hole=_from_dict(Hole, d.get("hole")),
            slots=[_from_dict(Slot, s) for s in d.get("slots", d.get("slot", []))],
        )
        if "palette" in d:
            t.palette = list(d["palette"])
        if "fallback_fonts" in d:
            t.fallback_fonts = list(d["fallback_fonts"])
        return t

    def save(self, path: str | Path) -> None:
        Path(path).write_text(tomli_w.dumps(self.to_dict()), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> Template:
        return cls.from_dict(tomllib.loads(Path(path).read_text(encoding="utf-8")))


@dataclass
class Printer:
    name: str = "Generic 220 × 220"
    bed_width: float = 220.0
    bed_depth: float = 220.0
    margin: float = 5.0  # keep-out from the bed edge
    gap: float = 4.0  # space between cards
    nozzle: float = 0.4
    layer_height: float = 0.2
    first_layer_height: float = 0.2
    # Thinnest stroke / gap that is expected to print; 0 = nozzle diameter.
    min_feature: float = 0.0
    allow_rotation: bool = True
    max_per_plate: int = 0  # 0 = as many as fit

    @property
    def feature_limit(self) -> float:
        return self.min_feature or self.nozzle

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Printer:
        return _from_dict(cls, d)

    # -- layer maths -----------------------------------------------------
    def snap_base(self, thickness: float) -> float:
        """Snap the card thickness to a whole number of layers."""
        h0, h = self.first_layer_height, self.layer_height
        n = max(1, _round_half_up((thickness - h0) / h) + 1)
        return round(h0 + (n - 1) * h, 4)

    def snap_relief(self, height: float) -> float:
        """Snap a raised height to a whole number of layers (at least one)."""
        h = self.layer_height
        return round(max(1, _round_half_up(height / h)) * h, 4)

    def layers_below(self, z: float) -> int:
        """Number of whole layers printed before height ``z``."""
        h0, h = self.first_layer_height, self.layer_height
        if z <= h0 + 1e-6:
            return 1 if z > 1e-6 else 0
        return 1 + _round_half_up((z - h0) / h)

    def layer_starting_at(self, z: float) -> int:
        """1-based layer number (as shown in Cura's preview) that starts at ``z``."""
        return self.layers_below(z) + 1


PRINTER_PRESETS: list[Printer] = [
    Printer("Generic 220 × 220", 220, 220),
    Printer("Creality Ender-3 / V2 / S1", 220, 220),
    Printer("Creality K1 / K1C", 220, 220),
    Printer("Creality Ender-3 V3 / K2", 220, 220),
    Printer("Prusa MK4 / MK3S+", 250, 210),
    Printer("Prusa MINI", 180, 180),
    Printer("Prusa CORE One", 250, 220),
    Printer("Bambu Lab X1 / P1 / P2", 256, 256),
    Printer("Bambu Lab A1", 256, 256),
    Printer("Bambu Lab A1 mini", 180, 180),
    Printer("UltiMaker S5", 330, 240),
    Printer("UltiMaker S3 / S7", 230, 190),
    Printer("Anycubic Kobra 2 / 3", 220, 220),
    Printer("Elegoo Neptune 4 Pro", 225, 225),
    Printer("Voron 2.4 350", 350, 350),
]


@dataclass
class Band:
    """A height band: everything whose top lands in it shows the same colour."""

    index: int
    z_top: float
    z_bottom: float
    colour: str
    features: list[str]


def height_bands(template: Template, printer: Printer) -> list[Band]:
    """Work out the colour bands implied by the template's heights."""
    base = printer.snap_base(template.card.thickness)
    tops: dict[float, list[str]] = {}
    if template.border.enabled:
        tops.setdefault(round(base + printer.snap_relief(template.border.height), 4), []).append(
            "Border"
        )
    for s in template.slots:
        if s.enabled:
            tops.setdefault(round(base + printer.snap_relief(s.height), 4), []).append(s.name)
    bands = [Band(0, base, 0.0, _palette(template, 0), ["Card"])]
    prev = base
    for i, z in enumerate(sorted(tops), start=1):
        bands.append(Band(i, z, prev, _palette(template, i), tops[z]))
        prev = z
    return bands


def _palette(template: Template, i: int) -> str:
    if i < len(template.palette):
        return template.palette[i]
    return DEFAULT_PALETTE[i % len(DEFAULT_PALETTE)]


@dataclass
class ColourChange:
    layer: int  # 1-based, as in Cura's preview
    z: float
    colour: str
    band: int


def colour_changes(template: Template, printer: Printer) -> list[ColourChange]:
    """Filament swaps needed, skipping bands that reuse the previous colour."""
    bands = height_bands(template, printer)
    changes: list[ColourChange] = []
    for prev, band in zip(bands, bands[1:]):
        if band.colour.lower() != prev.colour.lower():
            changes.append(
                ColourChange(printer.layer_starting_at(band.z_bottom), band.z_bottom, band.colour, band.index)
            )
    return changes


def _round_half_up(x: float) -> int:
    return math.floor(x + 0.5 + 1e-9)


def is_close(a: float, b: float) -> bool:
    return math.isclose(a, b, abs_tol=1e-6)
